(function () {
  'use strict';
  var step = 1, form = document.getElementById('application-form'), photoUrl = '';
  var names = ['Identitas', 'Foto dan riwayat', 'Kualifikasi', 'Pemeriksaan'];
  var adjust = { zoom: 1, x: 0, y: 0, rotate: 0 };
  function el(id) { return document.getElementById(id); }
  function updateStep() {
    document.querySelectorAll('.step-card').forEach(function (node) { node.classList.toggle('active', Number(node.dataset.step) === step); });
    el('progress').style.width = (step * 25) + '%'; el('step-label').textContent = step + ' dari 4'; el('step-name').textContent = names[step - 1];
    el('prev-btn').classList.toggle('hidden', step === 1); el('prev-placeholder').classList.toggle('hidden', step !== 1); el('next-btn').classList.toggle('hidden', step === 4); el('submit-btn').classList.toggle('hidden', step !== 4);
    if (step === 4) renderReview(); window.scrollTo({ top: 0, behavior: 'smooth' });
  }
  function requiredInStep() { return Array.prototype.slice.call(document.querySelectorAll('.step-card[data-step="' + step + '"] [required]')); }
  function validateStep() { var bad = requiredInStep().find(function (field) { return !field.checkValidity(); }); if (bad) { bad.reportValidity(); return false; } if (step === 3 && !['N1','N2'].includes(form.jlptLevel.value)) { showError('Posisi Japanese Interpreter saat ini memerlukan minimal JLPT N2.'); return false; } hideError(); return true; }
  function showError(message) { var box = el('form-error'); box.textContent = message; box.classList.remove('hidden'); }
  function hideError() { el('form-error').classList.add('hidden'); }
  function transformPhoto() { var img = el('photo-preview'); if (!img.src) return; img.style.transform = 'translate(calc(-50% + ' + adjust.x + '%), calc(-50% + ' + adjust.y + '%)) scale(' + adjust.zoom + ') rotate(' + adjust.rotate + 'deg)'; var side = el('side-photo'); if (side.src) side.style.objectPosition = (50 + adjust.x) + '% ' + (50 + adjust.y) + '%'; }
  function escapeAttribute(value) { return String(value || '').replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
  function createRow(type, data) { data = data || {}; var box = document.createElement('div'); box.className = 'timeline-row rounded-xl border border-border-light bg-surface-container-low p-3'; box.innerHTML = '<label class="text-xs font-bold text-outline">Mulai<input class="field mt-1" type="month" value="' + escapeAttribute(data.startDate || '') + '" data-key="startDate" aria-label="Tanggal mulai, opsional"></label><label class="text-xs font-bold text-outline">Selesai<input class="field mt-1" type="month" value="' + escapeAttribute(data.endDate || '') + '" data-key="endDate" aria-label="Tanggal selesai, opsional"></label><input class="field timeline-detail self-end" maxlength="180" placeholder="' + (type === 'education' ? 'Sekolah, universitas, atau jenjang pendidikan' : 'Perusahaan, jabatan, dan pengalaman interpreter') + '" value="' + escapeAttribute(data.detail || '') + '" data-key="detail" required><button class="remove-row mt-2 self-end text-secondary" type="button" aria-label="Hapus riwayat"><span class="material-symbols-outlined">delete</span></button>'; box.querySelector('.remove-row').addEventListener('click', function () { box.remove(); }); return box; }
  function collectRows(type) { return Array.prototype.slice.call(el(type + '-list').children).map(function (row) { return { startDate: row.querySelector('[data-key="startDate"]').value, endDate: row.querySelector('[data-key="endDate"]').value, detail: row.querySelector('[data-key="detail"]').value }; }); }
  function renderReview() { var fd = new FormData(form), edu = collectRows('education'), exp = collectRows('experience'); el('review-box').innerHTML = '<dl class="grid gap-5 text-sm sm:grid-cols-2"><div><dt class="text-xs font-bold uppercase tracking-label text-outline">Nama</dt><dd class="mt-1 font-semibold text-primary">' + escapeHtml(fd.get('fullName')) + '</dd></div><div><dt class="text-xs font-bold uppercase tracking-label text-outline">Email</dt><dd class="mt-1 font-semibold text-primary">' + escapeHtml(fd.get('email')) + '</dd></div><div><dt class="text-xs font-bold uppercase tracking-label text-outline">JLPT</dt><dd class="mt-1 font-semibold text-primary">' + escapeHtml(fd.get('jlptLevel')) + ' · ' + escapeHtml(fd.get('jlptYear')) + '</dd></div><div><dt class="text-xs font-bold uppercase tracking-label text-outline">Riwayat</dt><dd class="mt-1 font-semibold text-primary">' + edu.length + ' pendidikan, ' + exp.length + ' pengalaman kerja</dd></div></dl>'; }
  function escapeHtml(v) { var d = document.createElement('div'); d.textContent = v || ''; return d.innerHTML; }
  document.querySelectorAll('.add-row').forEach(function (button) { button.addEventListener('click', function () { var type = button.dataset.list, list = el(type + '-list'); if (list.children.length >= (type === 'education' ? 8 : 12)) return; list.appendChild(createRow(type)); }); });
  el('education-list').appendChild(createRow('education')); el('experience-list').appendChild(createRow('experience'));
  el('next-btn').addEventListener('click', function () { if (!validateStep()) return; step += 1; updateStep(); }); el('prev-btn').addEventListener('click', function () { step -= 1; updateStep(); });
  el('photo-input').addEventListener('change', function (event) { var file = event.target.files[0]; if (!file) return; if (file.size > 5 * 1024 * 1024) { event.target.value = ''; alert('Ukuran foto maksimal 5 MB.'); return; } if (photoUrl) URL.revokeObjectURL(photoUrl); photoUrl = URL.createObjectURL(file); el('photo-preview').src = photoUrl; el('photo-preview').classList.remove('hidden'); el('side-photo').src = photoUrl; el('side-photo').classList.remove('hidden'); transformPhoto(); });
  ['photo-zoom','photo-x','photo-y','photo-rotate'].forEach(function (id) { el(id).addEventListener('input', function () { adjust[id.replace('photo-','').replace('rotate','rotate')] = Number(el(id).value); transformPhoto(); }); });
  el('photo-reset').addEventListener('click', function () { adjust = { zoom: 1, x: 0, y: 0, rotate: 0 }; el('photo-zoom').value = 1; el('photo-x').value = 0; el('photo-y').value = 0; el('photo-rotate').value = 0; transformPhoto(); });
  ['fullName','email'].forEach(function (name) { form.elements[name].addEventListener('input', function () { el(name === 'fullName' ? 'side-name' : 'side-email').textContent = this.value || (name === 'fullName' ? 'Nama kandidat' : 'email@anda.com'); }); });
  form.addEventListener('submit', async function (event) { event.preventDefault(); if (!validateStep()) return; var button = el('submit-btn'), fd = new FormData(form); fd.append('education', JSON.stringify(collectRows('education'))); fd.append('experience', JSON.stringify(collectRows('experience'))); fd.append('photoAdjustment', JSON.stringify(adjust)); button.disabled = true; button.textContent = 'Membuat CV...'; hideError(); try { var response = await fetch('/api/career-submit', { method: 'POST', body: fd }); var out = await response.json(); if (!response.ok) throw new Error(out.error || 'Aplikasi belum dapat diproses.'); form.innerHTML = '<div class="py-12 text-center"><span class="material-symbols-outlined text-5xl text-secondary">mark_email_read</span><h2 class="mt-5 font-noto text-3xl font-bold text-primary">CV sedang dikirim</h2><p class="mx-auto mt-3 max-w-md text-sm leading-relaxed text-on-surface-variant">Kami telah mengirim tautan privat CV ke <strong>' + escapeHtml(out.email) + '</strong>. Tautan berlaku selama 30 hari.</p></div>'; } catch (err) { showError(err.message); button.disabled = false; button.textContent = 'Kirim dan buat CV'; } });
}());
